apiVersion: batch/v1
kind: CronJob
metadata:
  name: drift-monitor
  namespace: ray
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: drift-monitor
              image: stirlingw/homelab-evidently:latest
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-credentials
                      key: postgres-password
