apiVersion: apps/v1
kind: Deployment
metadata:
  name: homelab-fastapi
  namespace: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homelab-fastapi
  template:
    metadata:
      labels:
        app: homelab-fastapi
    spec:
      containers:
        - name: homelab-fastapi
          image: stirlingw/homelab-fastapi:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlflow-credentials
                  key: postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: homelab-fastapi
  namespace: ray
  labels:
    app: homelab-fastapi
spec:
  selector:
    app: homelab-fastapi
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30800
  type: NodePort
