apiVersion: batch/v1
kind: Job
metadata:
  name: xgboost-training
  namespace: ray
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: training
          image: stirlingw/homelab-training:latest
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.mlflow.svc.cluster.local:80"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio.mlflow.svc.cluster.local:9000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-credentials
                  key: minio-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-credentials
                  key: minio-password
