apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgboost-serve
  namespace: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgboost-serve
  template:
    metadata:
      labels:
        app: xgboost-serve
    spec:
      containers:
        - name: xgboost-serve
          image: stirlingw/xgboost-ray-serve:latest
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio.mlflow.svc.cluster.local:9000"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mlflow-credentials
                  key: minio-user
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mlflow-credentials
                  key: minio-password
---
apiVersion: v1
kind: Service
metadata:
  name: xgboost-serve
  namespace: ray
spec:
  selector:
    app: xgboost-serve
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
