apiVersion: v1
kind: Service
metadata:
  name: xgboost-serve
  namespace: ray
spec:
  selector:
    app: xgboost-serve
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgboost-serve
  namespace: ray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgboost-serve
  template:
    metadata:
      labels:
        app: xgboost-serve
    spec:
      containers:
        - name: xgboost-serve
          image: stirlingw/xgboost-ray-serve:latest
          ports:
            - containerPort: 8000
